### PR TITLE
[#92] 마이페이지 및 마이페이지 수정 페이지 ui 구현 

### PR DESCRIPTION
**Pull request by hijiyun**
## What is this PR? :mag:
1. 마이페이지 ui 완료
2. 닉네임 수정 페이지 ui 완료
3. 바텀시트 완료
4. 아이콘들 추가

## Changes :memo:
커밋 사이즈가 너무 커져버렸습니다 ... 제송합니다 .... ㅜㅜ 

## Screenshot :camera:

https://github.com/user-attachments/assets/27c8d447-f826-4367-9e8a-bc8eaf7b8bc5

### CODE REVIEW

**Comment by gihwan-dev** [comment]
<h2>Test Coverage</h2>
  
> dndproject@0.0.0 coverage /home/runner/work/dnd-11th-8-frontend/dnd-11th-8-frontend
> vitest run --coverage


<b><span style="color:#0AA"> RUN <span style="color:#FFF"><span style="font-weight:normal;text-decoration:none;font-style:normal"> <span style="color:#0AA">v2.0.5<span style="color:#FFF"> <span style="color:#555">/home/runner/work/dnd-11th-8-frontend/dnd-11th-8-frontend<span style="color:#FFF">
      Coverage enabled with <span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#A50">v8<span style="color:#FFF">

 <span style="color:#0A0">✓<span style="color:#FFF"> src/__test__/utils/validation.test.ts  (<span style="font-weight:normal;text-decoration:none;font-style:normal">2 tests<span style="font-weight:normal;text-decoration:none;font-style:normal">)<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> 3ms<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#FFF">
 <span style="color:#0A0">✓<span style="color:#FFF"> src/__test__/utils/dateUtils.test.ts  (<span style="font-weight:normal;text-decoration:none;font-style:normal">4 tests<span style="font-weight:normal;text-decoration:none;font-style:normal">)<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> 5ms<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#FFF">
 <span style="color:#0A0">✓<span style="color:#FFF"> src/__test__/utils/SomeTest.test.tsx  (<span style="font-weight:normal;text-decoration:none;font-style:normal">1 test<span style="font-weight:normal;text-decoration:none;font-style:normal">)<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> 87ms<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#FFF">
 <span style="color:#0A0">✓<span style="color:#FFF"> src/__test__/utils/sum.test.ts  (<span style="font-weight:normal;text-decoration:none;font-style:normal">1 test<span style="font-weight:normal;text-decoration:none;font-style:normal">)<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> 2ms<span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#FFF">

 Test Files <span style="font-weight:normal;text-decoration:none;font-style:normal"> <b><span style="color:#0A0">4 passed<span style="color:#FFF"><span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> (4)<span style="color:#FFF">
      Tests <span style="font-weight:normal;text-decoration:none;font-style:normal"> <b><span style="color:#0A0">8 passed<span style="color:#FFF"><span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#555"> (8)<span style="color:#FFF">
   Start at <span style="font-weight:normal;text-decoration:none;font-style:normal"> 06:47:40
   Duration <span style="font-weight:normal;text-decoration:none;font-style:normal"> 3.26s (transform 84ms, setup 793ms, collect 64ms, tests 97ms, environment 2.02s, prepare 426ms)<span style="font-weight:normal;text-decoration:none;font-style:normal">

<span style="color:#00A"> % <span style="color:#FFF">Coverage report from <span style="font-weight:normal;text-decoration:none;font-style:normal"><span style="color:#A50">v8<span style="color:#FFF">

</span></span></span></span></span></span></span></span></span></span></span></span></span></b></span></span></span></span></span></span></b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></b>
  ```text
  =============================== Coverage summary ===============================
  
Statements   : 0.18% ( 11/5944 )
Branches     : 8% ( 14/175 )
Functions    : 3.59% ( 6/167 )
Lines        : 0.18% ( 11/5944 )
================================================================================

  ```

**Comment by gihwan-dev** [comment]
```text
src/hooks/useInternalRouter.ts(13,3): error TS1109: Expression expected.
 ELIFECYCLE  Command failed with exit code 2.
Error: Command "pnpm run build" exited with 2
```
이런 빌드 에러가 뜨고 있네요...! 요거 수정 하시면 바로 merge 시킬게요~~!

**Comment by hijiyun** [comment]
> ```
> src/hooks/useInternalRouter.ts(13,3): error TS1109: Expression expected.
>  ELIFECYCLE  Command failed with exit code 2.
> Error: Command "pnpm run build" exited with 2
> ```
> 
> 이런 빌드 에러가 뜨고 있네요...! 요거 수정 하시면 바로 merge 시킬게요~~!

넵 ! 그래서 수정 해놨습니당 ~

**Comment by gihwan-dev** [comment]
> > ```
> > src/hooks/useInternalRouter.ts(13,3): error TS1109: Expression expected.
> >  ELIFECYCLE  Command failed with exit code 2.
> > Error: Command "pnpm run build" exited with 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이런 빌드 에러가 뜨고 있네요...! 요거 수정 하시면 바로 merge 시킬게요~~!
> 
> 넵 ! 그래서 수정 해놨습니당 ~

고생하셨습니다!

**Pull request merged**
